AllCops:
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '**/bin/*'
  TargetRubyVersion: 2.7.1
  DisplayCopNames: true
  NewCops: disable

Layout/AssignmentIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: true
  IgnoreEmptyMethods: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100 # Default: 10

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
